/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PushNotification } from "./PushNotification";
import { PushNotificationCountArgs } from "./PushNotificationCountArgs";
import { PushNotificationFindManyArgs } from "./PushNotificationFindManyArgs";
import { PushNotificationFindUniqueArgs } from "./PushNotificationFindUniqueArgs";
import { DeletePushNotificationArgs } from "./DeletePushNotificationArgs";
import { PushNotificationService } from "../pushNotification.service";
@graphql.Resolver(() => PushNotification)
export class PushNotificationResolverBase {
  constructor(protected readonly service: PushNotificationService) {}

  async _pushNotificationsMeta(
    @graphql.Args() args: PushNotificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PushNotification])
  async pushNotifications(
    @graphql.Args() args: PushNotificationFindManyArgs
  ): Promise<PushNotification[]> {
    return this.service.pushNotifications(args);
  }

  @graphql.Query(() => PushNotification, { nullable: true })
  async pushNotification(
    @graphql.Args() args: PushNotificationFindUniqueArgs
  ): Promise<PushNotification | null> {
    const result = await this.service.pushNotification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PushNotification)
  async deletePushNotification(
    @graphql.Args() args: DeletePushNotificationArgs
  ): Promise<PushNotification | null> {
    try {
      return await this.service.deletePushNotification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
